export const doubleSprintId = 2;

export const doubleCapacityTestData = [
  {
    groupCode: "test",
    name: "tester",
    sprintId: 1,
    workingDays: 10,
    md: 10,
    outOfOffice: 0,
    releases: 0,
    fridayProjects: 0,
    maintenance: 0,
  },
  {
    groupCode: "test",
    name: "tester2",
    sprintId: 1,
    workingDays: 8,
    md: 4,
    outOfOffice: 0,
    releases: 0,
    fridayProjects: 2,
    maintenance: 2,
  },
  {
    groupCode: "test",
    name: "tester3",
    sprintId: 1,
    workingDays: 10,
    md: 2,
    outOfOffice: 8,
    releases: 0,
    fridayProjects: 0,
    maintenance: 0,
  },
  {
    groupCode: "test",
    name: "tester",
    sprintId: 2,
    workingDays: 10,
    md: 8,
    outOfOffice: 2,
    releases: 0,
    fridayProjects: 0,
    maintenance: 0,
  },
  {
    groupCode: "test",
    name: "tester2",
    sprintId: 2,
    workingDays: 8,
    md: 5,
    outOfOffice: 0,
    releases: 0,
    fridayProjects: 1,
    maintenance: 2,
  },
  {
    groupCode: "test",
    name: "tester3",
    sprintId: 2,
    workingDays: 10,
    md: 4,
    outOfOffice: 6,
    releases: 0,
    fridayProjects: 0,
    maintenance: 0,
  }
];

export const doubleSprintTestData = [
  {
    groupCode: "test",
    sprintId: 1,
    planned: 30,
    added: 0,
    removed: 0,
    totalCompleted: 15,
    totalMd: 14,
    plannedCompletedDifference: 0.5,
  },
  {
    groupCode: "test",
    sprintId: 2,
    planned: 25,
    added: 0,
    removed: 0,
    totalCompleted: 0,
    totalMd: 17,
    plannedCompletedDifference: 0,
  }
];

export const doubleProgressTestData = [
  {
    groupCode: "test",
    sprintId: 1,
    name: "tester",
    workAssigned: 9,
    workCompleted: 7,
    averagePerMd: 0.7,
  },
  {
    groupCode: "test",
    sprintId: 1,
    name: "tester2",
    workAssigned: 7,
    workCompleted: 5,
    averagePerMd: 1.25,
  },
  {
    groupCode: "test",
    sprintId: 1,
    name: "tester3",
    workAssigned: 3,
    workCompleted: 3,
    averagePerMd: 1.5,
  },
  {
    groupCode: "test",
    sprintId: 2,
    name: "tester",
    workAssigned: 0,
    workCompleted: 0,
    averagePerMd: 0,
  },
  {
    groupCode: "test",
    sprintId: 2,
    name: "tester2",
    workAssigned: 0,
    workCompleted: 0,
    averagePerMd: 0,
  },
  {
    groupCode: "test",
    sprintId: 2,
    name: "tester3",
    workAssigned: 0,
    workCompleted: 0,
    averagePerMd: 0,
  }
];